name: NotesLock
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

#Dependencies used for operations in app
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # database storage
  sqflite: ^2.0.0+3
  # display todos in grid
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  #For Authentication
  local_auth: ^2.1.0
  #plugin for manipulating Android WindowManager LayoutParams dynamically at application run-time
  flutter_windowmanager: ^0.2.0
  # format DateTime
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  #assests used
  assets:
    - assets/images/
